title: Zhiguo Yan's Homepage
page-top-title: Zhiguo Yan
top-section-bg-text: Stochastic control; Reinforcement Learning
home-subtitle: Zhiguo Yan&ensp;|&ensp;严志国
copyright-text: '&copy; Zhiguo Yan 2023-2026. All Rights Reserved.'
